### ISSUE TITLE
Sample App Link

### ISSUE THREAD

**Issue by helensimonson** [hoist/Hoist#130]
Maybe make it clearer that the sample app is the Hello World app that is already there? The Hello World link in the table could have a little note after the link saying (this is a sample app) or something more fun, and the link in the get started section could have something saying (this is the sample app on the left, you can see all the pretty code here) or that general idea.

**Comment by mejamiewilson** [comment]
We're going to remove the onboarding flow that's there now, so there won't be a Hello World app for them to start with.
