### ISSUE TITLE
Feedback Blurb on Dashboard

### ISSUE THREAD

**Issue by helensimonson** [hoist/Hoist#133]
Maybe this blurb "If you have any feedback, we'd love to hear it. Just click the speech bubble in the bottom right of the screen." should be under the get started list? It is not as important as first actions?

The title could be "Welcome to Hoist, to get started you can:"

**Comment by helensimonson** [comment]
Maybe each option - Docs, Sample App and Create App could have a little description under them? I don't know if that would be needed but might help people make their desicion?

**Comment by mejamiewilson** [comment]
<img width="544" alt="screen shot 2015-08-10 at 4 55 12 pm" src="https://cloud.githubusercontent.com/assets/40936/9187023/97855258-3f80-11e5-9a18-a2b2522c4654.png">
@helensimonson thoughts on that content?
