### ISSUE TITLE
Maybe add a "choose connector" title or something to the connectors icon page

### ISSUE THREAD

**Issue by helensimonson** [hoist/Hoist#139]
It's pretty self explanatory that these are the connectors we have to pick from, but adding some kind of title above the icons to make it super explicit might be nice 

<img width="1058" alt="screen shot 2015-08-10 at 10 19 57 am" src="https://cloud.githubusercontent.com/assets/13734442/9177961/6a75ee76-3f49-11e5-80a7-7bbf690a85e3.png">

**Comment by mejamiewilson** [comment]
<img width="580" alt="screen shot 2015-08-10 at 4 45 57 pm" src="https://cloud.githubusercontent.com/assets/40936/9186913/4e9c296e-3f7f-11e5-9484-34561234bb5f.png">
