### ISSUE TITLE
Connector compatibility table

### ISSUE THREAD

**Issue by buildmaster** [hoist/Hoist#147]
we need a table for each connector marking if it can be used for polling, public, private, documentation and sample links.

**Comment by buildmaster** [comment]
also a column next to polling called 'webhooks' - incase the connector implements webhooks instead of polling. there should be some kind of greyed out cell if the API doesn't support it (if it does, the polling cells will probably be greyed out too)

**Comment by helensimonson** [comment]
How about this table?

![10 8 15 connectors table-01](https://cloud.githubusercontent.com/assets/13734442/9187635/9d6283a6-3f87-11e5-9105-31aee65b53d1.png)
