### ISSUE TITLE
Console content not showing up in beta

### ISSUE THREAD

**Issue by mejamiewilson** [hoist/Hoist#174]

**Comment by buildmaster** [comment]
yes it is

**Comment by buildmaster** [comment]
if you get a console error at any point, that's the bug and then other errors are usually because of that bug, but console content is showing up on mine

**Comment by buildmaster** [comment]
![screenshot 2016-04-05 14 15 21](https://cloud.githubusercontent.com/assets/19946/14269441/de4139d6-fb38-11e5-9d9b-6c05db355f54.png)

**Comment by buildmaster** [comment]
I've upped the max messages per call to 300
